Propagate Tag from PVC to PV
mtougeron/k8s-pvc-tagger pull request #68
Opened 2022-08-05 16:23 UTC by speedfl

Closes #66

Annotate PV from PVCs label

2022-08-05 16:39 UTC, mtougeron commented
Awesome, I can't wait to review this! :)

2022-08-08 13:49 UTC, speedfl commented
@mtougeron for information I am not a big fan of the name "propagate-to-pv" but I am not good finding names. So if you have an idea don't hesitate :D

2022-10-02 21:34 UTC, mtougeron requested changes
I'm so sorry, I thought I had submitted this review weeks ago but it's been sitting here pending. Just some minor feedback.

2022-10-02 21:34 UTC, mtougeron commented on README.md
> +`--propate-to-pv` - Allow to propagate labels and annotations from PVC to PV. Adding computed tags as annotation with prefix: `k8s-pvc-tagger/tags/`
What if we used `--add-metadata-to-pv`? Would that work? I'm horrible at naming too.

2022-10-02 21:34 UTC, mtougeron commented on kubernetes.go
> +	newPV, err := k8sClient.CoreV1().PersistentVolumes().Update(context.TODO(), pv, metav1.UpdateOptions{})
Instead of `newPV` let's call this `updatedPV`

2022-10-02 21:34 UTC, mtougeron commented on kubernetes.go
> +		return "", nil, pv, err
If there's an error getting the PV then we should probably return nil for it.

2022-10-02 21:34 UTC, mtougeron commented on kubernetes.go
> +		return "", nil, pv, errors.New("cannot get PVC annotations")
Let's be consistent and return nil for the PV in the event of errors like it does for the pvc

2023-12-24 21:49 UTC, closed without merging